# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  containerRegistry: 'dotnetacrv1.azurecr.io'
  imageRepository: 'dotnetrepo'
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      inputs:
        containerRegistry: 'dotnetacr'
        repository: 'dotnetrepo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        
    - task: KubernetesManifest@1
      inputs:
        action: 'createSecret'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'akssvnlatest'
        namespace: 'default'
        secretType: 'dockerRegistry'
        secretName: 'dotnetsecret'
        dockerRegistryEndpoint: 'dotnetacr'
    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'akssvnlatest'
        namespace: 'default'
        manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
        imagePullSecrets: 'dotnetsecret'
        containers: |
                $(containerRegistry)/$(imageRepository):$(tag)