version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $DOCKERHUB_USERNAME
      - echo $DOCKERHUB_PASS     
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS      
  build:
    commands:
      - echo Restoring dependencies...     
      - echo Building the application...     
      - echo Publishing the application...    
      - echo Building the Docker image...     
      - docker build -t dotnetappsjenkins .
      - echo Tagging image with tag "$IMAGE_TAG"...
      - echo Tagging image with tag $IMAGE_URI:latest
      - docker tag dotnetappsjenkins $IMAGE_URI:latest
  post_build:
    commands:
      - echo Pushing the Docker image to docker push ..
      - docker push $IMAGE_URI:latest
      - echo write definitions file...
      - printf '[{"name":"dotnetapppipeline","imageUri":"%s"}]' $IMAGE_URI:latest> imagedefinitions.json

artifacts:
  files: imagedefinitions.json
