version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $DOCKERHUB_USERNAME
      - echo $DOCKERHUB_PASS
      - $(aws ecr get-login-password --region $AWS_DEFAULT_REGION) | docker login --username AWS --password-stdin $ECR_REPO_URI
       
  build:
    commands:
      - echo Restoring dependencies...     
      - echo Building the application...     
      - echo Publishing the application...    
      - echo Building the Docker image...     
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_REPO_URIFULL:$IMAGE_TAG      
     
  post_build:
    commands:
      - echo Pushing the Docker image to docker push ..
      - docker push $ECR_REPO_URIFULL:$IMAGE_TAG
      - echo write definitions file...
      - printf '[{"name":"dotnetapppipeline","imageUri":"%s"}]' $ECR_REPO_URI:$IMAGE_TAG> imagedefinitions.json

artifacts:
  files: imagedefinitions.json
